name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:

  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Linting
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.50

  build-test:

    runs-on: ubuntu-latest

    needs: [check]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build & Test
      run: go test -json ./... > test.json

    - name: Annotate tests
      if: always()
      uses: guyarb/golang-test-annotations@v0.6.0
      with:
        test-results: test.json

    - name: Functional Test
      run: make functional

    - name: Upload Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test.json
